"""Define relationship between idea and category

Revision ID: 091eb19c66d5
Revises: a7e021c974c9
Create Date: 2018-03-18 14:32:59.838475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091eb19c66d5'
down_revision = 'a7e021c974c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'idea_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('idea_tag', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
