"""Update idea table

Revision ID: 73f3750b4b91
Revises: ac095cd89f86
Create Date: 2018-03-18 11:02:23.704334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f3750b4b91'
down_revision = 'ac095cd89f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcomment', sa.Column('sub_comment', sa.String(), nullable=True))
    op.drop_column('subcomment', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcomment', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('subcomment', 'sub_comment')
    # ### end Alembic commands ###
