"""Update idea table

Revision ID: ac095cd89f86
Revises: 4ae276d824af
Create Date: 2018-03-18 09:12:07.476706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac095cd89f86'
down_revision = '4ae276d824af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('category', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('subcomment', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('subcomment', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_column('subcomment', 'created_date')
    op.drop_column('subcomment', 'created_at')
    op.drop_column('category', 'created_date')
    op.drop_column('category', 'created_at')
    # ### end Alembic commands ###
