"""empty message

Revision ID: c049048a22e0
Revises: 5d85208d07fa
Create Date: 2018-04-21 15:29:12.235758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c049048a22e0'
down_revision = '5d85208d07fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_name_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_name_key', 'user', ['name'])
    # ### end Alembic commands ###
