"""empty message

Revision ID: ce863b986fd8
Revises: 7c5276ab8627
Create Date: 2018-03-16 21:32:27.439713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce863b986fd8'
down_revision = '7c5276ab8627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idea', sa.Column('join_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date')
    op.drop_column('idea', 'join_date')
    # ### end Alembic commands ###
