"""empty message

Revision ID: e51059757c0f
Revises: ce863b986fd8
Create Date: 2018-03-16 21:58:37.751090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e51059757c0f'
down_revision = 'ce863b986fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idea', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.drop_column('idea', 'join_date')
    op.add_column('user', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.drop_column('user', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user', 'created_date')
    op.add_column('idea', sa.Column('join_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('idea', 'created_date')
    # ### end Alembic commands ###
